### ISSUE TITLE
energized limb 2h

### ISSUE THREAD

**Issue by jgdn93** [kite1348/MorgarOT-Issue-Tracker#12]
Energized limb is 2 handed. Looks like based on wiki, it should be 1 handed.

**Comment by kite1348** [comment]
> Energized limb is 2 handed. Looks like based on wiki, it should be 1 handed.

I can't see where on the article it says two-handed
https://tibia.fandom.com/wiki/Energized_Limb
is this the one?

**Comment by jgdn93** [comment]
it doesn't say it's 2 handed either though lol, idk. I thought it was just 1h, someone reported it as bug

**Comment by kite1348** [comment]
It might be, I'll change it, according to this page it's part of a set in which you also wear a book so we'll go with that for now.

https://www.tibiawiki.com.br/wiki/Magic_Level_Set
