### ISSUE TITLE
House splitt in two

### ISSUE THREAD

**Issue by mrhultin** [kite1348/MorgarOT-Issue-Tracker#3]
**Describe the bug**
There is a house, or two I should say. That are separated by nothing, Theater Avenue 12 & Magician's Alley 1 looks to be one house, but are acctually two.
**To Reproduce**
1. Go to 32307, 31796, 7.
2. Enter while invinted to one of the house but not both.
3. Try to move around at will.

**Expected behavior**
Should be a wall or something.

**Comment by kite1348** [comment]
This issue will be fixed after today's SS, a wall has been added to separate the houses.
