### ISSUE TITLE
Rainbow shield enchantment

### ISSUE THREAD

**Issue by jgdn93** [kite1348/MorgarOT-Issue-Tracker#8]
Enchantments on rainbow shields deplete even when you don't use the shield.

**Comment by mrhultin** [comment]
This is how it works on real-Tibia aswell, actually

**Comment by kite1348** [comment]
> This is how it works on real-Tibia aswell, actually

I know since its an ot we can pick between what is to be implemented, would it be qol change to not deplete? Is it even worth to look into it?

**Comment by jgdn93** [comment]
probably not tbh, rainbow shield isn't used for anything other than deco
